# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 817)
        MainWindow.setStyleSheet("background-color: #1b1d23;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.viewWidget = QtWidgets.QWidget(self.frame_2)
        self.viewWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewWidget.setStyleSheet("color:rgb(85, 170, 255);")
        self.viewWidget.setObjectName("viewWidget")
        self.gridLayout.addWidget(self.viewWidget, 0, 0, 1, 4)
        self.frameRayCast = QtWidgets.QFrame(self.frame_2)
        self.frameRayCast.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(39, 44, 54);\n"
"border: none;")
        self.frameRayCast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRayCast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRayCast.setObjectName("frameRayCast")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameRayCast)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ambientSlider = QtWidgets.QSlider(self.frameRayCast)
        self.ambientSlider.setOrientation(QtCore.Qt.Vertical)
        self.ambientSlider.setObjectName("ambientSlider")
        self.verticalLayout_14.addWidget(self.ambientSlider)
        self.AmbientLabel = QtWidgets.QLabel(self.frameRayCast)
        font = QtGui.QFont()
        font.setFamily("Oswald Light")
        font.setPointSize(12)
        font.setBold(False)
        self.AmbientLabel.setFont(font)
        self.AmbientLabel.setStyleSheet("color:rgb(255, 255, 255);")
        self.AmbientLabel.setObjectName("AmbientLabel")
        self.verticalLayout_14.addWidget(self.AmbientLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.diffuseSlider = QtWidgets.QSlider(self.frameRayCast)
        self.diffuseSlider.setOrientation(QtCore.Qt.Vertical)
        self.diffuseSlider.setObjectName("diffuseSlider")
        self.verticalLayout_20.addWidget(self.diffuseSlider)
        self.DiffuseLabel = QtWidgets.QLabel(self.frameRayCast)
        font = QtGui.QFont()
        font.setFamily("Oswald Light")
        font.setPointSize(12)
        font.setBold(False)
        self.DiffuseLabel.setFont(font)
        self.DiffuseLabel.setStyleSheet("color:rgb(255, 255, 255);")
        self.DiffuseLabel.setObjectName("DiffuseLabel")
        self.verticalLayout_20.addWidget(self.DiffuseLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.specularSlider = QtWidgets.QSlider(self.frameRayCast)
        self.specularSlider.setOrientation(QtCore.Qt.Vertical)
        self.specularSlider.setObjectName("specularSlider")
        self.verticalLayout_19.addWidget(self.specularSlider)
        self.SpecularLabel = QtWidgets.QLabel(self.frameRayCast)
        font = QtGui.QFont()
        font.setFamily("Oswald Light")
        font.setPointSize(12)
        font.setBold(False)
        self.SpecularLabel.setFont(font)
        self.SpecularLabel.setStyleSheet("color:rgb(255, 255, 255);")
        self.SpecularLabel.setObjectName("SpecularLabel")
        self.verticalLayout_19.addWidget(self.SpecularLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_19)
        self.gridLayout.addWidget(self.frameRayCast, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(39, 44, 54);\n"
"border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loadButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("-apple-system")
        font.setPointSize(12)
        font.setBold(True)
        self.loadButton.setFont(font)
        self.loadButton.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  backface-visibility: hidden;\n"
"  background-color: #405cf5;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  font-size: 100%;\n"
"  height: 35px;\n"
"  line-height: 1.15;\n"
"\n"
"  outline: none;\n"
"  overflow: hidden;\n"
"  padding: 0 5px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-transform: none;\n"
"  transform: translateZ(0);\n"
"  transition: all .2s,box-shadow .08s ease-in;\n"
"  touch-action: manipulation;\n"
"  width:50%;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/upload-square-svgrepo-com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadButton.setIcon(icon)
        self.loadButton.setIconSize(QtCore.QSize(25, 25))
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout_2.addWidget(self.loadButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.iso_slider = QtWidgets.QSlider(self.frame)
        self.iso_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iso_slider.setObjectName("iso_slider")
        self.verticalLayout.addWidget(self.iso_slider)
        self.isoValue = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Oswald Light")
        font.setPointSize(14)
        font.setBold(False)
        self.isoValue.setFont(font)
        self.isoValue.setStyleSheet("color:rgb(255, 255, 255);")
        self.isoValue.setObjectName("isoValue")
        self.verticalLayout.addWidget(self.isoValue)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.surfaceRadio = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.surfaceRadio.setFont(font)
        self.surfaceRadio.setStyleSheet("color:rgb(255, 255, 255);")
        self.surfaceRadio.setObjectName("surfaceRadio")
        self.horizontalLayout.addWidget(self.surfaceRadio)
        self.rayCastRadio = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.rayCastRadio.setFont(font)
        self.rayCastRadio.setStyleSheet("color:rgb(255, 255, 255);")
        self.rayCastRadio.setObjectName("rayCastRadio")
        self.horizontalLayout.addWidget(self.rayCastRadio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.realTimeCheck = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.realTimeCheck.setFont(font)
        self.realTimeCheck.setStyleSheet("color:rgb(255, 255, 255);")
        self.realTimeCheck.setObjectName("realTimeCheck")
        self.horizontalLayout_2.addWidget(self.realTimeCheck)
        self.renderButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("-apple-system")
        font.setPointSize(12)
        font.setBold(True)
        self.renderButton.setFont(font)
        self.renderButton.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  backface-visibility: hidden;\n"
"  background-color: #405cf5;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"  box-sizing: border-box;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  font-size: 100%;\n"
"  height: 35px;\n"
"  line-height: 1.15;\n"
"\n"
"  outline: none;\n"
"  overflow: hidden;\n"
"  padding: 0 5px;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  text-transform: none;\n"
"  transform: translateZ(0);\n"
"  transition: all .2s,box-shadow .08s ease-in;\n"
"  touch-action: manipulation;\n"
"  width:100%;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}\n"
"")
        self.renderButton.setIconSize(QtCore.QSize(25, 25))
        self.renderButton.setObjectName("renderButton")
        self.horizontalLayout_2.addWidget(self.renderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AmbientLabel.setText(_translate("MainWindow", "Ambient"))
        self.DiffuseLabel.setText(_translate("MainWindow", "Diffuse"))
        self.SpecularLabel.setText(_translate("MainWindow", "Specular"))
        self.loadButton.setText(_translate("MainWindow", "Load DICOM files"))
        self.isoValue.setText(_translate("MainWindow", "ISO Value:"))
        self.surfaceRadio.setText(_translate("MainWindow", "Surface Rendering"))
        self.rayCastRadio.setText(_translate("MainWindow", "RayCast Rendering"))
        self.realTimeCheck.setText(_translate("MainWindow", "Real Time"))
        self.renderButton.setText(_translate("MainWindow", "Render"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
